//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeConditionsConditionObservation) DeepCopyInto(out *AttributeConditionsConditionObservation) {
	*out = *in
	if in.CaseSensitive != nil {
		in, out := &in.CaseSensitive, &out.CaseSensitive
		*out = new(bool)
		**out = **in
	}
	if in.DynamicKey != nil {
		in, out := &in.DynamicKey, &out.DynamicKey
		*out = new(string)
		**out = **in
	}
	if in.DynamicKeySource != nil {
		in, out := &in.DynamicKeySource, &out.DynamicKeySource
		*out = new(string)
		**out = **in
	}
	if in.EntityID != nil {
		in, out := &in.EntityID, &out.EntityID
		*out = new(string)
		**out = **in
	}
	if in.EnumValue != nil {
		in, out := &in.EnumValue, &out.EnumValue
		*out = new(string)
		**out = **in
	}
	if in.IntegerValue != nil {
		in, out := &in.IntegerValue, &out.IntegerValue
		*out = new(float64)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.StringValue != nil {
		in, out := &in.StringValue, &out.StringValue
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeConditionsConditionObservation.
func (in *AttributeConditionsConditionObservation) DeepCopy() *AttributeConditionsConditionObservation {
	if in == nil {
		return nil
	}
	out := new(AttributeConditionsConditionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeConditionsConditionParameters) DeepCopyInto(out *AttributeConditionsConditionParameters) {
	*out = *in
	if in.CaseSensitive != nil {
		in, out := &in.CaseSensitive, &out.CaseSensitive
		*out = new(bool)
		**out = **in
	}
	if in.DynamicKey != nil {
		in, out := &in.DynamicKey, &out.DynamicKey
		*out = new(string)
		**out = **in
	}
	if in.DynamicKeySource != nil {
		in, out := &in.DynamicKeySource, &out.DynamicKeySource
		*out = new(string)
		**out = **in
	}
	if in.EntityID != nil {
		in, out := &in.EntityID, &out.EntityID
		*out = new(string)
		**out = **in
	}
	if in.EnumValue != nil {
		in, out := &in.EnumValue, &out.EnumValue
		*out = new(string)
		**out = **in
	}
	if in.IntegerValue != nil {
		in, out := &in.IntegerValue, &out.IntegerValue
		*out = new(float64)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.StringValue != nil {
		in, out := &in.StringValue, &out.StringValue
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeConditionsConditionParameters.
func (in *AttributeConditionsConditionParameters) DeepCopy() *AttributeConditionsConditionParameters {
	if in == nil {
		return nil
	}
	out := new(AttributeConditionsConditionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeConditionsObservation) DeepCopyInto(out *AttributeConditionsObservation) {
	*out = *in
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = make([]AttributeConditionsConditionObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeConditionsObservation.
func (in *AttributeConditionsObservation) DeepCopy() *AttributeConditionsObservation {
	if in == nil {
		return nil
	}
	out := new(AttributeConditionsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeConditionsParameters) DeepCopyInto(out *AttributeConditionsParameters) {
	*out = *in
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = make([]AttributeConditionsConditionParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeConditionsParameters.
func (in *AttributeConditionsParameters) DeepCopy() *AttributeConditionsParameters {
	if in == nil {
		return nil
	}
	out := new(AttributeConditionsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeRuleObservation) DeepCopyInto(out *AttributeRuleObservation) {
	*out = *in
	if in.AttributeConditions != nil {
		in, out := &in.AttributeConditions, &out.AttributeConditions
		*out = make([]AttributeConditionsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AzureToPgpropagation != nil {
		in, out := &in.AzureToPgpropagation, &out.AzureToPgpropagation
		*out = new(bool)
		**out = **in
	}
	if in.AzureToServicePropagation != nil {
		in, out := &in.AzureToServicePropagation, &out.AzureToServicePropagation
		*out = new(bool)
		**out = **in
	}
	if in.CustomDeviceGroupToCustomDevicePropagation != nil {
		in, out := &in.CustomDeviceGroupToCustomDevicePropagation, &out.CustomDeviceGroupToCustomDevicePropagation
		*out = new(bool)
		**out = **in
	}
	if in.EntityType != nil {
		in, out := &in.EntityType, &out.EntityType
		*out = new(string)
		**out = **in
	}
	if in.HostToPgpropagation != nil {
		in, out := &in.HostToPgpropagation, &out.HostToPgpropagation
		*out = new(bool)
		**out = **in
	}
	if in.PgToHostPropagation != nil {
		in, out := &in.PgToHostPropagation, &out.PgToHostPropagation
		*out = new(bool)
		**out = **in
	}
	if in.PgToServicePropagation != nil {
		in, out := &in.PgToServicePropagation, &out.PgToServicePropagation
		*out = new(bool)
		**out = **in
	}
	if in.ServiceToHostPropagation != nil {
		in, out := &in.ServiceToHostPropagation, &out.ServiceToHostPropagation
		*out = new(bool)
		**out = **in
	}
	if in.ServiceToPgpropagation != nil {
		in, out := &in.ServiceToPgpropagation, &out.ServiceToPgpropagation
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeRuleObservation.
func (in *AttributeRuleObservation) DeepCopy() *AttributeRuleObservation {
	if in == nil {
		return nil
	}
	out := new(AttributeRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeRuleParameters) DeepCopyInto(out *AttributeRuleParameters) {
	*out = *in
	if in.AttributeConditions != nil {
		in, out := &in.AttributeConditions, &out.AttributeConditions
		*out = make([]AttributeConditionsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AzureToPgpropagation != nil {
		in, out := &in.AzureToPgpropagation, &out.AzureToPgpropagation
		*out = new(bool)
		**out = **in
	}
	if in.AzureToServicePropagation != nil {
		in, out := &in.AzureToServicePropagation, &out.AzureToServicePropagation
		*out = new(bool)
		**out = **in
	}
	if in.CustomDeviceGroupToCustomDevicePropagation != nil {
		in, out := &in.CustomDeviceGroupToCustomDevicePropagation, &out.CustomDeviceGroupToCustomDevicePropagation
		*out = new(bool)
		**out = **in
	}
	if in.EntityType != nil {
		in, out := &in.EntityType, &out.EntityType
		*out = new(string)
		**out = **in
	}
	if in.HostToPgpropagation != nil {
		in, out := &in.HostToPgpropagation, &out.HostToPgpropagation
		*out = new(bool)
		**out = **in
	}
	if in.PgToHostPropagation != nil {
		in, out := &in.PgToHostPropagation, &out.PgToHostPropagation
		*out = new(bool)
		**out = **in
	}
	if in.PgToServicePropagation != nil {
		in, out := &in.PgToServicePropagation, &out.PgToServicePropagation
		*out = new(bool)
		**out = **in
	}
	if in.ServiceToHostPropagation != nil {
		in, out := &in.ServiceToHostPropagation, &out.ServiceToHostPropagation
		*out = new(bool)
		**out = **in
	}
	if in.ServiceToPgpropagation != nil {
		in, out := &in.ServiceToPgpropagation, &out.ServiceToPgpropagation
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeRuleParameters.
func (in *AttributeRuleParameters) DeepCopy() *AttributeRuleParameters {
	if in == nil {
		return nil
	}
	out := new(AttributeRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DimensionConditionsConditionObservation) DeepCopyInto(out *DimensionConditionsConditionObservation) {
	*out = *in
	if in.ConditionType != nil {
		in, out := &in.ConditionType, &out.ConditionType
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.RuleMatcher != nil {
		in, out := &in.RuleMatcher, &out.RuleMatcher
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DimensionConditionsConditionObservation.
func (in *DimensionConditionsConditionObservation) DeepCopy() *DimensionConditionsConditionObservation {
	if in == nil {
		return nil
	}
	out := new(DimensionConditionsConditionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DimensionConditionsConditionParameters) DeepCopyInto(out *DimensionConditionsConditionParameters) {
	*out = *in
	if in.ConditionType != nil {
		in, out := &in.ConditionType, &out.ConditionType
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.RuleMatcher != nil {
		in, out := &in.RuleMatcher, &out.RuleMatcher
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DimensionConditionsConditionParameters.
func (in *DimensionConditionsConditionParameters) DeepCopy() *DimensionConditionsConditionParameters {
	if in == nil {
		return nil
	}
	out := new(DimensionConditionsConditionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DimensionConditionsObservation) DeepCopyInto(out *DimensionConditionsObservation) {
	*out = *in
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = make([]DimensionConditionsConditionObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DimensionConditionsObservation.
func (in *DimensionConditionsObservation) DeepCopy() *DimensionConditionsObservation {
	if in == nil {
		return nil
	}
	out := new(DimensionConditionsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DimensionConditionsParameters) DeepCopyInto(out *DimensionConditionsParameters) {
	*out = *in
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = make([]DimensionConditionsConditionParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DimensionConditionsParameters.
func (in *DimensionConditionsParameters) DeepCopy() *DimensionConditionsParameters {
	if in == nil {
		return nil
	}
	out := new(DimensionConditionsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DimensionRuleObservation) DeepCopyInto(out *DimensionRuleObservation) {
	*out = *in
	if in.AppliesTo != nil {
		in, out := &in.AppliesTo, &out.AppliesTo
		*out = new(string)
		**out = **in
	}
	if in.DimensionConditions != nil {
		in, out := &in.DimensionConditions, &out.DimensionConditions
		*out = make([]DimensionConditionsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DimensionRuleObservation.
func (in *DimensionRuleObservation) DeepCopy() *DimensionRuleObservation {
	if in == nil {
		return nil
	}
	out := new(DimensionRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DimensionRuleParameters) DeepCopyInto(out *DimensionRuleParameters) {
	*out = *in
	if in.AppliesTo != nil {
		in, out := &in.AppliesTo, &out.AppliesTo
		*out = new(string)
		**out = **in
	}
	if in.DimensionConditions != nil {
		in, out := &in.DimensionConditions, &out.DimensionConditions
		*out = make([]DimensionConditionsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DimensionRuleParameters.
func (in *DimensionRuleParameters) DeepCopy() *DimensionRuleParameters {
	if in == nil {
		return nil
	}
	out := new(DimensionRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleObservation) DeepCopyInto(out *RuleObservation) {
	*out = *in
	if in.AttributeRule != nil {
		in, out := &in.AttributeRule, &out.AttributeRule
		*out = make([]AttributeRuleObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DimensionRule != nil {
		in, out := &in.DimensionRule, &out.DimensionRule
		*out = make([]DimensionRuleObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EntitySelector != nil {
		in, out := &in.EntitySelector, &out.EntitySelector
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleObservation.
func (in *RuleObservation) DeepCopy() *RuleObservation {
	if in == nil {
		return nil
	}
	out := new(RuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleParameters) DeepCopyInto(out *RuleParameters) {
	*out = *in
	if in.AttributeRule != nil {
		in, out := &in.AttributeRule, &out.AttributeRule
		*out = make([]AttributeRuleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DimensionRule != nil {
		in, out := &in.DimensionRule, &out.DimensionRule
		*out = make([]DimensionRuleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EntitySelector != nil {
		in, out := &in.EntitySelector, &out.EntitySelector
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleParameters.
func (in *RuleParameters) DeepCopy() *RuleParameters {
	if in == nil {
		return nil
	}
	out := new(RuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneV2) DeepCopyInto(out *ZoneV2) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneV2.
func (in *ZoneV2) DeepCopy() *ZoneV2 {
	if in == nil {
		return nil
	}
	out := new(ZoneV2)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZoneV2) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneV2List) DeepCopyInto(out *ZoneV2List) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZoneV2, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneV2List.
func (in *ZoneV2List) DeepCopy() *ZoneV2List {
	if in == nil {
		return nil
	}
	out := new(ZoneV2List)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZoneV2List) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneV2Observation) DeepCopyInto(out *ZoneV2Observation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.LegacyID != nil {
		in, out := &in.LegacyID, &out.LegacyID
		*out = new(string)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]ZoneV2RulesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneV2Observation.
func (in *ZoneV2Observation) DeepCopy() *ZoneV2Observation {
	if in == nil {
		return nil
	}
	out := new(ZoneV2Observation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneV2Parameters) DeepCopyInto(out *ZoneV2Parameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.LegacyID != nil {
		in, out := &in.LegacyID, &out.LegacyID
		*out = new(string)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]ZoneV2RulesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneV2Parameters.
func (in *ZoneV2Parameters) DeepCopy() *ZoneV2Parameters {
	if in == nil {
		return nil
	}
	out := new(ZoneV2Parameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneV2RulesObservation) DeepCopyInto(out *ZoneV2RulesObservation) {
	*out = *in
	if in.Rule != nil {
		in, out := &in.Rule, &out.Rule
		*out = make([]RuleObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneV2RulesObservation.
func (in *ZoneV2RulesObservation) DeepCopy() *ZoneV2RulesObservation {
	if in == nil {
		return nil
	}
	out := new(ZoneV2RulesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneV2RulesParameters) DeepCopyInto(out *ZoneV2RulesParameters) {
	*out = *in
	if in.Rule != nil {
		in, out := &in.Rule, &out.Rule
		*out = make([]RuleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneV2RulesParameters.
func (in *ZoneV2RulesParameters) DeepCopy() *ZoneV2RulesParameters {
	if in == nil {
		return nil
	}
	out := new(ZoneV2RulesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneV2Spec) DeepCopyInto(out *ZoneV2Spec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneV2Spec.
func (in *ZoneV2Spec) DeepCopy() *ZoneV2Spec {
	if in == nil {
		return nil
	}
	out := new(ZoneV2Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneV2Status) DeepCopyInto(out *ZoneV2Status) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneV2Status.
func (in *ZoneV2Status) DeepCopy() *ZoneV2Status {
	if in == nil {
		return nil
	}
	out := new(ZoneV2Status)
	in.DeepCopyInto(out)
	return out
}
