apiVersion: v1
kind: Secret
metadata:
  name: dynatrace-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "dt_env_url": "https://<your-env-id>.live.dynatrace.com",
      "iam_account_id": "<your-iam-account-id>",
      "iam_client_id": "<your-iam-client-id>",
      "iam_client_secret": "<your-iam-client-secret>"
    }
---
apiVersion: dynatrace-native.crossplane.io/v1alpha1
kind: ClusterProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: dynatrace-creds
      key: credentials
